### ISSUE TITLE
hi~我想提一个需求：路书

### ISSUE THREAD

**Issue by Lpbzzz** [JserWang/rc-bmap#140]
路书就是轨迹回放...

本身项目的需求中也有【轨迹回放】。一开始我做的就是不停地 setstate 点的位置。假设两个点之间距离较远，这样的回放就会变成点位瞬间移动了，正常的回放应该是连续移动的。我从网上找了网上的 Lushu 代码，clone了一份 放到了npm上 （‘react-lushu’ ） ，然后根据示例自己做了个。其实我觉得一般项目用到地图，多多少少都有类似需求。所以，能不能把它加上。
Thanks♪(･ω･)ﾉ

**Comment by JserWang** [comment]
Hi，我在试想着把各种library做成三方可插拔的形态，这样可以在不动rc-bmap的源码就可让使用者用到自己想要的library。
每个人使用地图组件都可能有不同的目的，做成可插拔的效果后，可以保证主题rc-bmap包是足够小的，就像现在热力图、测距工具、弧线等等都可以从主体中剥离。

**Comment by Lpbzzz** [comment]
这样也挺好。核心包可以保证性能，插件集可以多样拓展！
