### ISSUE TITLE
Cannot read property 'lng' of undefined,Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by shleyZ** [JserWang/rc-bmap#33]
[InfoWindow](https://bmap.jser-club.com/guide/overlay.html#infowindow-%E4%BF%A1%E6%81%AF%E7%AA%97%E5%8F%A3),[Polyline](https://bmap.jser-club.com/guide/overlay.html#polyline-%E6%8A%98%E7%BA%BF).....覆盖类 都有这个问题，提交新版本时，先测试一下哦

**Comment by JserWang** [comment]
升级0.1.7即可，感谢提醒，后面会引入自动化测试工具。

**Comment by shleyZ** [comment]
Thank you for your effort.
